"""Fonctions du domaine ROUTAGE pour Larry MCL."""
import importlib
from LSL_MCL_VARIABLES import *  # Paramètres utilisés aussi dans les arguments par défaut.

class LSL_MCL_Routages:
    """Opérations routage du modèle."""

    @staticmethod
    def alpha_palette_dxt5(a0, a1):
        """
        Implémente le traitement interne `alpha_palette_dxt5` utilisé par le pipeline de localisation ou de diagnostic.
    
        Paramètres:
            a0, a1.
    
        Connexions:
            Appelée par : alpha_dxt5.
            Appelle : aucune autre fonction interne directe détectée.
        """
        if a0 > a1:

            return [
                a0,
                a1,
                (6 * a0 + a1) // 7,
                (5 * a0 + 2 * a1) // 7,
                (4 * a0 + 3 * a1) // 7,
                (3 * a0 + 4 * a1) // 7,
                (2 * a0 + 5 * a1) // 7,
                (a0 + 6 * a1) // 7,
            ]

        return [
            a0,
            a1,
            (4 * a0 + a1) // 5,
            (3 * a0 + 2 * a1) // 5,
            (2 * a0 + 3 * a1) // 5,
            (a0 + 4 * a1) // 5,
            0,
            255,
        ]


    @staticmethod
    def resoudre_option(nom):
        """Retrouve une opération exposée par une classe du projet."""
        return getattr(getattr(importlib.import_module(_OPERATIONS[nom][0]), _OPERATIONS[nom][1]), nom) if nom in _OPERATIONS else None

_OPERATIONS = {
    'dossier_image_classee': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'chemin_image_classee': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'creer_dossiers_images': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'creer_marqueur_backup_disable': ('LSL_MCL_BACKUP', 'LSL_MCL_Backup'),
    'calculer_ratio_proximite': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'construire_memoire_jam_globale': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'generer_ecran_sierra_localise': ('LSL_MCL_BASE64', 'LSL_MCL_Base64'),
    'installer_ffmpeg': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'installer_afspacker': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'installer_sfd_muxer': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'installer_sfd_muxer_original': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'charger_module_local': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'installer_module_local': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'copier_dossier': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'migrer_dossier_legacy': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'migrer_fichier_legacy': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'creer_arborescence': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'chemins_version_probables': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    '_installation_pc_valide': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    '_candidats_jeu_depuis_racine': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'detecter_jeu': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'lire_marqueur_localisation_pc': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'ecrire_marqueur_localisation_pc': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'backup_pc': ('LSL_MCL_BACKUP', 'LSL_MCL_Backup'),
    'ps2_contient_donnees': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'lister_lecteurs_windows': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'trouver_entree_racine_ci': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'trouver_executable_ps2': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'telecharger': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'titre': ('LSL_MCL_MENU', 'LSL_MCL_Menu'),
    'log': ('LSL_MCL_MENU', 'LSL_MCL_Menu'),
    'sha256': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'supprimer': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'detecter_ps2_monte': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'copier_ps2_depuis_lecteur': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'preparer_ps2': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'dimensions_pillow': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'bmp_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'dds_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'jpg_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'png_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'webp_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'gif_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'ico_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'image_valide': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'scanner_images_jam_mmap': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'dossier_extraction_images_ps2': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'extraction_images_ps2_complete': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'index_noms_jam_pc_pour_images': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'nom_image_ps2_normalise': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'extraire_images_ps2_version': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'extraire_images': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'nom_jam': ('LSL_MCL_JAMS', 'LSL_MCL_jams'),
    'normaliser_bmp_image': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'normaliser_bmp': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'rgb565': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'rgb565_inverse': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'palette_couleur': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'bloc_couleur': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'pixels_bloc': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'encoder_dxt': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'infos_dds': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'reconstruire_dds': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'remplir_slot': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'encoder_generique': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'cle_image': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'appliquer_padding_espaces_jam': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'injecter_images': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'jam_chunks': ('LSL_MCL_JAMS', 'LSL_MCL_jams'),
    'blocs_texte': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'parse_chaines': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'score_langue': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'score_francais': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'adapter_fr': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'source_ps2_index': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'trouver_ps2_jam': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'choisir_bloc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'diagnostiquer_livre_noir': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'verifier_references_techniques': ('LSL_MCL_REFERENCES_TECHNICS', 'LSL_MCL_References_technics'),
    'rechercher_aos_suspect': ('LSL_MCL_REFERENCES_AOS', 'LSL_MCL_References_aos'),
    'remplacer_chunk_variable': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'construire_appinit_673': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'construire_payload_fr_complet': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'construire_payload_compact_fixe': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'normaliser_texte_jam': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'normaliser_source_anglaise_jam': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'variables_texte_jam': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    '_suffixe_apres_derniere_variable': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    '_texte_console_normalise': ('LSL_MCL_CONSOLE_PS2', 'LSL_MCL_Console_ps2'),
    '_phrase_pc_complete': ('LSL_MCL_CONSOLE_PS2', 'LSL_MCL_Console_ps2'),
    '_retirer_clause_console_texte': ('LSL_MCL_CONSOLE_PS2', 'LSL_MCL_Console_ps2'),
    'adapter_variables_ps2_vers_pc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    '_separer_commandes_jam': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MLLoadQ': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MLLoadng': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MSSave': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MDDelete': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MSSaveQ': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MDDeletQ': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MEMCRDL1': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traiter_MIGSerch': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'adapter_cle_ps2_vers_pc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'adapter_texte_ps2_vers_pc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'choisir_traduction_globale': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'parse_chaines_multiples': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'construire_memoire_jam_globale': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'choisir_bloc_structurel': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'conserver_commandes_pc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'corriger_texte_temps_stats': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'corriger_compteur_choses_trouvees': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'corriger_polices_objectif': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'patch_textes_menus_fr': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traduire_jam_sans_deplacement': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'charger_adaptations_pc': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'limiter_texte_ais': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'payload_ais_est_valide': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'finaliser_textes_pc_specifiques': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traduire_appinit': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'traduire_autres_jam': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'generer_guide_geometrie': ('LSL_MCL_GEOMETRIES', 'LSL_MCL_Geometries'),
    'patch_geometrie_v3': ('LSL_MCL_GEOMETRIES', 'LSL_MCL_Geometries'),
    'aligner': ('LSL_MCL_GEOMETRIES', 'LSL_MCL_Geometries'),
    'analyser_entete_adx': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'analyser_jam_detaille': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'lire_afs': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'construire_afs': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'nom_afs': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'trouver_fichier_ci': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'localiser_afs_gameplay': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'localiser_adx_afs': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'outil': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'commande': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'muxer_sfd_robuste': ('LSL_MCL_VIDEOS', 'LSL_MCL_Videos'),
    'encoder_audio_taille_pc': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'configurer_langue_personnalisee': ('LSL_MCL_VIDEOS', 'LSL_MCL_Videos'),
    'detecter_langues_ps2': ('LSL_MCL_LANGUAGES', 'LSL_MCL_Languages'),
    'demander_langue_localisation': ('LSL_MCL_LANGUAGES', 'LSL_MCL_Languages'),
    'localiser_cinema': ('LSL_MCL_VIDEOS', 'LSL_MCL_Videos'),
    'remplacer_audio_sfd_direct': ('LSL_MCL_VIDEOS', 'LSL_MCL_Videos'),
    'traduire_tous_jam_localises': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'trouver_index_audio_langue': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'trouver_paquets_audio_sfd': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'marqueurs_audio_langue': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    'alpha_dxt3': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'alpha_palette_dxt5': ('LSL_MCL_ROUTAGE', 'LSL_MCL_Routages'),
    'alpha_dxt5': ('LSL_MCL_IMAGES', 'LSL_MCL_Images'),
    'choisir_entree_audio_langue': ('LSL_MCL_AUDIOS', 'LSL_MCL_Audios'),
    '_jam2_acx_u16': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_u32': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_p32': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_lire': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_adx_info': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_scanner': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_reconstruire': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    '_jam2_acx_injecter': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    'localiser_audio_jam2_acx_multilangue': ('LSL_MCL_ACX', 'LSL_MCL_Acx'),
    'construire_version_fr': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'executer_fonction_optionnelle': ('LSL_MCL_MENU', 'LSL_MCL_Menu'),
    'fermer_larry': ('LSL_MCL_COMPUTER', 'LSL_MCL_Computer'),
    'initialiser': ('LSL_MCL_MAIN', 'LSL_MCL_Main'),
    'injecter_ecran_sierra_localise': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'injecter_langue_ps2': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'injecter_images_depuis_menu': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'injecter_data_version_edit_fini': ('LSL_MCL_INJECTIONS', 'LSL_MCL_Injection'),
    'main': ('LSL_MCL_MAIN', 'LSL_MCL_Main'),
    'menu': ('LSL_MCL_MENU', 'LSL_MCL_Menu'),
    'normaliser_code_langue': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'obtenir_data_de_travail': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'obtenir_source_pc_construction': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'restaurer_data_version_backup': ('LSL_MCL_BACKUP', 'LSL_MCL_Backup'),
    'texte_contient_marqueur_langue': ('LSL_MCL_LANGUAGES', 'LSL_MCL_Languages'),
    'trouver_fichier_langue': ('LSL_MCL_LANGUAGES', 'LSL_MCL_Languages'),
    'verifier_structure_jam': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'verifier_outils': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'empreinte_sha256': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'extraire_entrees_textes_jam': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
    'identifier_langue_bloc_texte': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'identifier_langue_bloc_texte': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'identifier_type_fichier': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'normaliser_chemin_jam': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'score_francais_bloc': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'analyser_adaptations_console_vers_pc': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'analyser_fichier_complet': ('LSL_MCL_ANALISES', 'LSL_MCL_Analises'),
    'assurer_outils': ('LSL_MCL_OUTILS', 'LSL_MCL_Outils'),
    'diagnostiquer_menus_interfaces': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_jam_pc_ps2': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_cles_textes_pc_ps2': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_localisation_ps2': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_textes_jam': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_jeu_complet': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'diagnostiquer_videos_audio': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'indexer_inventaire': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'inventorier_source_complete': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'preparer_contexte_diagnostic_cible': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'preparer_diagnostic_complet': ('LSL_MCL_DIAGNOSTICS', 'LSL_MCL_Diagnostics'),
    'trier_blocs_par_langue': ('LSL_MCL_TEXTES', 'LSL_MCL_Textes'),
    'demander_iso_ps2': ('LSL_MCL_EXTRACTIONS', 'LSL_MCL_Extractions'),
}
